### ISSUE TITLE
Collection only downloading first page or 2 

### ISSUE THREAD

**Issue by bobcat24** [HuggableSquare/vsco-dl#6]
Only getting 40 images from a 100+ page collection with -c

**Comment by HuggableSquare** [comment]
oof, ran into a snag with git 🤦‍♂, but I pushed a commit that should fix your problem.

Apparently the collections api for vsco has a hard limit of 60 images per page, but since we were requesting 1000 when the api said the total was 61 the script thought it had everything. I set the page size for collections requests to 60, so hopefully that solves the problem for you!

**Comment by HuggableSquare** [comment]
Going to close this since the problem should be fixed, if you have any more issues feel free to open a new issue. 🙂
